const {
  REACT_APP_DEVELOPMENT_SERVER_URL,
  REACT_APP_PRODUCTION_SERVER_URL,
  NODE_ENV,
} = process.env;

const URL = REACT_APP_DEVELOPMENT_SERVER_URL;
if (NODE_ENV === "production") URL = REACT_APP_PRODUCTION_SERVER_URL;

export default URL;
