export default [
    {
        id: 1,
        name1: "C",
        name2: "C++",
        title: "General Purpose programming language",
        img: "https://source.unsplash.com/400x200/?language,programming",
    },
    {
        id: 2,
        name1: "HTML",
        name2: "CSS",
        title: "Markup language",
        img: "https://source.unsplash.com/400x200/?language,programming",
    },
    {
        id: 3,
        name1: "Javascript",
        name2: "Bootstarp",
        title: "Styling language",
        img: "https://source.unsplash.com/400x200/?language,programming",
    },
    {
        id: 4,
        name1: "React",
        name2: "Material UI",
        title: "General Purpose programming language",
        img: "https://source.unsplash.com/400x200/?language,programming",
    },
    {
        id: 5,
        name1: "Node js",
        name2: "Express JS",
        title: "Javascript library for frontend",
        img: "https://source.unsplash.com/400x200/?language,programming",
    },
    {
        id: 6,
        name1: "MongoDB",
        name2: "Mongoose",
        title: "Run time enveroment for server",
        img: "https://source.unsplash.com/400x200/?language,programming",
    },
    {
        id: 7,
        name1: "Redux",
        name2: "GraphQL",
        title: "Run time enveroment for server",
        img: "https://source.unsplash.com/400x200/?language,programming",
    },
    {
        id: 8,
        name1: "Python",
        name2: "Data Structure",
        title: "No SQL Database",
        img: "https://source.unsplash.com/400x200/?language,programming",
    },
]